services:
  pg:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB:       ${PG_DB}
      POSTGRES_USER:     ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg_movies_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"            # kun hvis du vil tilgå DB’en fra host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      retries: 5

volumes:
  pg_movies_data:
